### PR TITLE
Aws pinia

### PR DESCRIPTION
**Pull request by asagilmore**
This branch is a fork of the "aws" branch. It uses the same logic to read files from the datasets using the aws-sdk, but uses a state manager called Pinia for better code readability and reliability.

### CODE REVIEW

**Comment by arokem** [comment]
I mean "rebase on top of main"

**Comment by arokem** [comment]
I think that if you rebase this on top of master, you should get only the
unique changes between this and the main branch appearing here.

**Comment by asagilmore** [comment]
rebased to main!

**Comment by asagilmore** [comment]
I have added ESLint to the dev dependencies here. I added a script to lint the project in the package.json. To lint just run `$npm run lint`

**Pull request merged**
