### PR TITLE
Niivue Upgrade

### PR DESCRIPTION
**Pull request by asagilmore**

### CODE REVIEW

**Comment by asagilmore** [comment]
This PR updates tractoscopes dependencies to be compatible with the latest (0.39.0) version of Niivue. It also removes a number of unneccicary dependencies, and fully removes the use of the AWS-SDK. 

currently experiencing some weirdness with the bundle selection where it shows the last selected bundle in the dropdown. it is fully functional, but confusing to the user. Working to solve currently.

**Comment by asagilmore** [comment]
I have fixed the issue where all bundles were shown on loading of trx. The tract profile selector showing last selected tract is fixed on my local machine, but still appears to be an issue on the deploy preview. Not sure if there could be a difference between the dev build vs production build.

**Comment by arokem** [comment]
OK - I think that we can go ahead and merge this, and then we can see whether this appears in production as well. 

One more (small?) request: Could we set the default to toggle all the bundles on at start up?

**Comment by asagilmore** [comment]
Made all tracts selected by default, should be good to merge.

**Comment by arokem** [comment]
Hmm. I'm not seeing all the bundles toggled on in the preview, but I'll go ahead and merge this and we can fix it up on a subsequent PR.

**Pull request merged**
