### PR TITLE
Cors fix

### PR DESCRIPTION
**Pull request by asagilmore**
This is a fix that manually creates and parses a listObjectsV2 request instead of using the aws-sdk. This is done to avoid the cors error, as manually creating this request skips a preflight request, and instead includes the cors header in the same request.

### CODE REVIEW

**Comment by arokem** [comment]
This is great! I can see that the app finds the filenames for HCP now, and loads the maps properly. For some reason, the tractography trx files are not loading, though.

**Comment by asagilmore** [comment]
> This is great! I can see that the app finds the filenames for HCP now, and loads the maps properly. For some reason, the tractography trx files are not loading, though.

Yes, all the cors issues are fixed, but there is currently an issue where when you switch datasets its try's to get the trk file before it knows that the dataset has trx files instead, so I am working on fixing that.

**Comment by asagilmore** [comment]
This pull request has tract selection for trx files disabled. Other than that is fully supports the hcp dataset.

**Comment by arokem** [comment]
OK - let's go ahead and merge this for now, and we can work on the tract selection on a subsequent PR.

**Pull request merged**
